services:
    jrc.checkout_flow_plugin.controller.checkout_start:
        class: Jrc\CheckoutFlowPlugin\Controller\CheckoutStartController
        arguments:
            - "@sylius.context.channel"
            - '@router'
            - "%jrc.checkout_flow_plugin.route_map%"
    
    jrc.checkout_flow_plugin.form.extension.checkout_flow_configuration:
        class: Jrc\CheckoutFlowPlugin\Form\Extension\CheckoutFlowConfigurationExtension
        arguments: ["%jrc.checkout_flow_plugin.sm_configs_choices%"]
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ChannelBundle\Form\Type\ChannelType }

    jrc.checkout_flow_plugin.listener.cart_update:
        class: Jrc\CheckoutFlowPlugin\EventListener\CartUpdateListener
        arguments: ["@sylius.repository.order"]
        tags:
            - { name: kernel.event_listener, event: sylius.channel.post_update, method: onChannelUpdate }
    
    jrc.checkout_flow_plugin.form.select_shipping_and_payment:
        class: Jrc\CheckoutFlowPlugin\Form\Type\Checkout\SelectShippingAndPaymentType
        arguments:
            - %sylius.model.order.class%
            - %sylius.form.type.order.validation_groups%
        tags:
            - { name: form.type }
    
    jrc.checkout_flow_plugin.form.address_select_shipping:
        class: Jrc\CheckoutFlowPlugin\Form\Type\Checkout\AddressAndSelectShippingType
        arguments:
            - "%sylius.model.order.class%"
            - "%sylius.form.type.order.validation_groups%"
        tags:
            - { name: form.type }
            
    jrc.checkout_flow_plugin.listener.group_checkout:
        class: Jrc\CheckoutFlowPlugin\Checkout\GroupCheckoutResolver
        arguments:
            - "@jrc.checkout_flow_plugin.matcher.group_checkout"
            - "@sylius.context.cart"
            - "@sylius.context.channel"
            - "%jrc.checkout_flow_plugin.flow_routes%"
        tags:
            - { name: kernel.event_subscriber }
            
    # decorated services
    jrc.checkout_flow_plugin.sm.factory:
        class: Jrc\CheckoutFlowPlugin\Factory\GroupFactory
        decorates: sm.factory
        arguments: 
            - "%sm.configs%"
            - "@event_dispatcher"
            - "@sm.callback_factory"
            - "%jrc.checkout_flow_plugin.sm_configs%"

    jrc.checkout_flow_plugin.router.group_checkout_state:
        class: Jrc\CheckoutFlowPlugin\Checkout\GroupCheckoutStateUrlGenerator
        decorates: sylius.router.checkout_state
        arguments: 
            - "@jrc.checkout_flow_plugin.router.group_checkout_state.inner"
            - "@sylius.context.channel"
            - "%jrc.checkout_flow_plugin.route_map%"
