# cart -> address -> select shipping -> select payment and complete
sylius_order_checkout_1:
    choice_label: 'Cart->Address->Shipping->Payment-and-Complete'
    route_map:
        empty_order:
            route: sylius_shop_cart_summary
        cart:
            route: sylius_shop_checkout_address
        addressed:
            route: sylius_shop_checkout_select_shipping
        shipping_selected:
            route: sylius_shop_checkout_select_payment_and_complete
    state_machine:
        class: "%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            addressed: ~
            shipping_selected: ~
            shipping_skipped: ~
            completed: ~
        transitions:
            address:
                from: [cart, addressed, shipping_selected, shipping_skipped, completed]
                to: addressed
            skip_shipping:
                from: [addressed]
                to: shipping_skipped
            select_shipping:
                from: [addressed, shipping_selected, complete]
                to: shipping_selected
            complete:
                from: [addressed, shipping_selected, shipping_skipped]
                to: completed
        callbacks:
            after:
                sylius_process_cart:
                    on: ["select_shipping", "address", "skip_shipping"]
                    do: ["@sylius.order_processing.order_processor", "process"]
                    args: ["object"]
                sylius_create_order:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'create'", "'sylius_order'"]
                sylius_save_checkout_completion_date:
                    on: ["complete"]
                    do: ["object", "completeCheckout"]
                    args: ["object"]
                sylius_skip_shipping:
                    on: ["address"]
                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
                    args: ["object"]
                    priority: 1
                sylius_control_payment_state:
                    on: ["complete"]
                    do: ["@sylius.state_resolver.order_payment", "resolve"]
                    args: ["object"]
                sylius_control_shipping_state:
                    on: ["complete"]
                    do: ["@sylius.state_resolver.order_shipping", "resolve"]
                    args: ["object"]
